id: I27C63B4B
legacy_id: P009623
ocr_import_info:
  bdrc_scan_id: W19997
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T23:42:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T03:55:43.640139+00:00'
last_modified: 2022-08-27 12:00:15.615746
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19997
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW19997
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཀར་མཛེས་ཁུལ་གྱི་དགོན་སྡེ་སོ་སོའི་ལོ་རྒྱུས་གསལ་བར་བཤད་པ།
statistics:
  ocr_word_mean_confidence_index: 0.8672984163264632
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1GS44629:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS44629
      total_pages: 704
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1GS44629.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8870857760510029
    legacy_id: v002
  I1GS44630:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS44630
      total_pages: 546
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1GS44630.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8966388117705848
    legacy_id: v003
  I1GS44628:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS44628
      total_pages: 335
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS44628.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.822968317978058
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
