id: I27C63B4B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:47:03+00:00'
last_modified: '2022-06-08T12:20:28.961164+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19997
  title: དཀར་མཛེས་ཁུལ་གྱི་དགོན་སྡེ་སོ་སོའི་ལོ་རྒྱུས་གསལ་བར་བཤད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    031C:
      image_group_id: I1GS44628
      title: ''
      total_pages: 335
      order: 1
      base_file: 031C.txt
    E29B:
      image_group_id: I1GS44629
      title: ''
      total_pages: 704
      order: 2
      base_file: E29B.txt
    0850:
      image_group_id: I1GS44630
      title: ''
      total_pages: 546
      order: 3
      base_file: 0850.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
